version: '3.8'

services:
  frontend:
    build:
      context: ./cs-frontend  
      dockerfile: Dockerfile 
    ports:
      - "4200:4200"
    depends_on:
      - backend

  backend:
    build:
      context: ./cs-backend  
      dockerfile: Dockerfile  
    ports:
      - "5001:5001"
